source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'VPNDemo' do
	pod 'AFNetworking', '~> 3.1.0'
	pod 'MKNetworkKit', '~> 0.87'
	pod 'ASIHTTPRequest', '~> 1.8.2'
	pod 'SDAutoLayout', '~>2.1.6'
	pod 'MBProgressHUD', '~> 1.0.0'
    pod 'MJRefresh'
end
